// GENERATED by scripts/sync-engine.mjs: parse/CodeParsers.kt 의 commentIdOf 부분 발췌
package bateaux.spt.coolnjoy.core.parse

import org.jsoup.nodes.Element

private val COMMENT_ROW_ID = Regex("""^c_(\d+)$""")
private val NA_GOOD_ID = Regex("""na_good\(\s*'[^']*'\s*,\s*'(\d+)'""")

/** 댓글 행의 번호: `id="c_N"`, 없으면 추천 링크 `a.na-cgood`의 onclick `na_good('보드', 'N', ...)`. */
internal fun commentIdOf(row: Element): Long? =
    COMMENT_ROW_ID.find(row.id())?.groupValues?.get(1)?.toLongOrNull()
        ?: row.selectFirst("a.na-cgood")?.attr("onclick")?.let { NA_GOOD_ID.find(it)?.groupValues?.get(1)?.toLongOrNull() }
